config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }

  devise_scope :usuario do
    root to: 'usuarios/sessions#new'
    get '/usuarios/sign_out', to: 'usuarios/sessions#destroy', as: :logout_usuario_session
  end

  authenticate :usuario do
    resources :clientes do
      resources :llamados, only: [:index, :show, :new, :create, :edit, :update]
      delete '/llamados/:id', to: 'llamados#destroy', as: 'cliente_llamado'
      

    end
    delete '/clientes/:id', to: 'clientes#destroy', as: 'eliminar_cliente'
    get 'pdf/generate', to: 'pdf#generate', as: 'generate_pdf'
  end
  
  # Resto de las rutas de tu aplicación
end

app/models/cliente.rb
class Cliente < ApplicationRecord
    has_many :llamados

    validates :numero_telefonico, presence: true
    validates :nombre, presence: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  end
  

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  def index
    @clientes = Cliente.all
  
    if params[:search].present?
      @clientes = @clientes.where("nombre LIKE :search OR email LIKE :search", search: "%#{params[:search]}%")
    end
  
    @clientes = @clientes.paginate(page: params[:page], per_page: 10)
  end
  

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(cliente_params)

    if @cliente.save
      flash[:notice] = 'CLIENTE CREADO EXITOSAMENTE'
      redirect_to clientes_path
    else
      flash.now[:alert] = 'NO SE PUDO CREAR CLIENTE'
      render :new
    end
  end

  def edit
  end

  def update
    if @cliente.update(cliente_params)
      redirect_to cliente_path(@cliente), notice: 'CLIENTE ACTUALIZADO CORRECTAMENTE'
    else
      render :edit
    end
  end

  def destroy
    # Encuentra y elimina los registros de llamados asociados al cliente
    Llamado.where(cliente_id: @cliente.id).destroy_all
  
    # Elimina el cliente
    @cliente.destroy
  
    redirect_to clientes_path, notice: 'CLIENTE ELIMINADO EXITOSAMENTE'
  end
  

  def show
    @llamado = @cliente.llamados.build
  end

  private

  def set_cliente
    @cliente = Cliente.find(params[:id])
  end

  def cliente_params
    params.require(:cliente).permit(:nombre, :email, :numero_telefonico)
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Numero telefonico:</strong>
    <%= cliente.numero_telefonico %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= cliente.nombre %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= cliente.email %>
  </p>

</div>

app/views/clientes/_form.html.erb
<style>
  .custom-form {
    background-color: black;
    color: white;
    padding: 20px;
  }
  
  .center-button {
    text-align: center;
  }
</style>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6 custom-form">
      <%= form_with(model: cliente) do |form| %>
        <div class="alert alert-danger" role="alert">
          <% if cliente.errors.any? %>
            <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

            <ul>
              <% cliente.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <div class="form-group">
          <%= form.label :numero_telefonico, class: "control-label" %>
          <%= form.text_field :numero_telefonico, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :nombre, class: "control-label" %>
          <%= form.text_field :nombre, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email, class: "control-label" %>
          <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group center-button">
          <%= form.submit "Guardar", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clientes/edit.html.erb
<BR><BR>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="custom-form bg-dark text-white p-4">
        <h1 class="text-center">EDITAR CLIENTE</h1>

        <%= form_with(model: @cliente, url: cliente_path(@cliente), method: :patch, html: {class: "needs-validation", novalidate: true}) do |form| %>
          <% if @cliente.errors.any? %>
            <div class="alert alert-danger">
              <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>
              <ul>
                <% @cliente.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <%= form.label :nombre, class: "form-label" %>
            <%= form.text_field :nombre, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :numero_telefonico, class: "form-label" %>
            <%= form.text_field :numero_telefonico, class: "form-control" %>
          </div>

          <div class="mb-3">
            <%= form.label :email, class: "form-label" %>
            <%= form.email_field :email, class: "form-control" %>
          </div>

          <div class="text-center">
            <%= form.submit 'Guardar cambios', class: "btn btn-primary" %>
          </div>
        <% end %>

        <div class="text-center mt-3">
          <%= link_to 'Cancelar', cliente_path(@cliente), class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clientes/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success text-center">
    <% Array(flash[:notice]).each do |message| %>
      <%= message %>
    <% end %>
  </div>
<% end %>


<br><br><br>

<div class="container">
  <div class="card text-center bg-dark text-white">
    <div class="card-body">
      <h1 class="card-title">CLIENTES</h1>
    </div>
  </div>
</div>

<div class="container">
  <%= form_tag(clientes_path, method: :get, class: "mb-3") do %>
    <div class="input-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Buscar clientes..." %>
      <div class="input-group-append">
        <%= submit_tag "Buscar", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

  <table class="table table-dark text-center">
    <thead>
      <tr>
        <th scope="col">Número Telefónico</th>
        <th scope="col">Nombre</th>
        <th scope="col">Email</th>
        <th scope="col">Acciones <%= link_to "AGREGAR CLIENTE", new_cliente_path, class: "btn btn-success" %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @clientes.each do |cliente| %>
        <tr>
          <td><%= cliente.numero_telefonico %></td>
          <td><%= cliente.nombre %></td>
          <td><%= cliente.email %></td>
          <td>
            <%= link_to "AGREGAR LLAMADAS", new_cliente_llamado_path(cliente), class: "btn btn-primary" %>
            <%= link_to "VER LLAMADAS", cliente_llamados_path(cliente), class: "btn btn-primary" %>
            <%= link_to "EDITAR", edit_cliente_path(cliente), class: "btn btn-secondary" %>
            <%= link_to "Eliminar", cliente_path(cliente), method: :delete, data: { confirm: "¿Estás seguro de eliminar este cliente?" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= will_paginate @clientes %>
</div>

app/views/clientes/new.html.erb
<BR><BR>
<center><h1>AGREGAR CLIENTES</h1></center>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <center><%= link_to "REGRESAR", clientes_path %></center>
</div>

app/views/clientes/show.html.erb
<BR><BR>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="custom-form bg-dark text-white p-4">
        <h1 class="text-center">Editar cliente</h1>

        <% if notice %>
          <p class="text-success"><%= notice %></p>
        <% end %>

        <%= render @cliente %>

        <div>
          <%= link_to "EDITAR", edit_cliente_path(@cliente), class: "btn btn-secondary" %> |
          <%= link_to "REGRESAR", clientes_path, class: "btn btn-secondary" %>
          <BR>

          <%= button_to "ELIMINAR", @cliente, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
          <BR>
          <%= link_to "MOSTRAR LLAMADOS", cliente_llamados_path(@cliente), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>