config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }

  devise_scope :usuario do
    root to: 'usuarios/sessions#new'
    get '/usuarios/sign_out', to: 'usuarios/sessions#destroy', as: :logout_usuario_session
  end

  authenticate :usuario do
    resources :clientes do
      resources :llamados, only: [:index, :show, :new, :create, :edit, :update]
      delete '/llamados/:id', to: 'llamados#destroy', as: 'cliente_llamado'
      

    end
    delete '/clientes/:id', to: 'clientes#destroy', as: 'eliminar_cliente'
    get 'pdf/generate', to: 'pdf#generate', as: 'generate_pdf'
  end
  
  # Resto de las rutas de tu aplicación
end

app/models/llamado.rb
class Llamado < ApplicationRecord
    belongs_to :cliente
  end
  

app/controllers/llamados_controller.rb
class LlamadosController < ApplicationController
  before_action :set_cliente
  before_action :set_llamado, only: [:show, :edit, :update, :destroy]

  # GET /clientes/:cliente_id/llamados
  def index
    @llamados = @cliente.llamados
  end

  # GET /clientes/:cliente_id/llamados/:id
  def show
  end

  # GET /clientes/:cliente_id/llamados/new
  def new
    @llamado = @cliente.llamados.build
  end

  # POST /clientes/:cliente_id/llamados
  def create
    @llamado = @cliente.llamados.build(llamado_params)

    if @llamado.save
      redirect_to cliente_llamados_path(@cliente), notice: "¡LLAMADO GUARDADO EXITOSAMENTE!"

    else
    
      render :new
    end
  end

  # GET /clientes/:cliente_id/llamados/:id/edit
  def edit
  end

  # PATCH/PUT /clientes/:cliente_id/llamados/:id
  def update
    if @llamado.update(llamado_params)
      redirect_to cliente_llamado_path(@cliente, @llamado), notice: "LLAMADO ACTUALIZADO EXITOSAMENTE"
    else
      render :edit
    end
  end

  # DELETE /clientes/:cliente_id/llamados/:id
  def destroy
    @llamado.destroy
    redirect_to cliente_llamados_path(@cliente), notice: "LLAMADO ELIMINADO EXITOSAMENTE"
  end
  

  private

  def set_cliente
    @cliente = Cliente.find(params[:cliente_id])
  end

  def set_llamado
    @llamado = @cliente.llamados.find(params[:id])
  end

  def llamado_params
    params.require(:llamado).permit(:motivo, :fecha)
  end
end

app/helpers/llamados_helper.rb
module LlamadosHelper
end

app/views/llamados/_form.html.erb
<%= form_with(model: [@cliente, @llamado]) do |form| %>
  <% if @llamado.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@llamado.errors.count, "error") %> prohibited this llamado from being saved:</h2>
      <ul>
        <% @llamado.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= form.label :motivo, style: "display: block" %>
    <%= form.select :motivo, ['Requerimiento', 'Reclamo', 'Consulta'], {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :fecha, style: "display: block" %>
    <%= form.date_field :fecha, class: "form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/llamados/_llamado.html.erb
<div id="<%= dom_id llamado %>">
  <p>
    <strong>Motivo:</strong>
    <%= llamado.motivo %>
  </p>

  <p>
    <strong>Fecha:</strong>
    <%= llamado.fecha %>
  </p>

</div>

app/views/llamados/edit.html.erb
<h1>Editing llamado</h1>

<%= render "form", llamado: @llamado %>

<br>

<div>
  <%= link_to "Show this llamado", @llamado %> |
  <%= link_to "Back to llamados", llamados_path %>
</div>

app/views/llamados/index.html.erb
<BR><BR><BR><BR>
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-success" role="alert">
      <%= value %>
    </div>
  <% end %>

  <!-- Resto del contenido de la vista -->
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      
      
      <div class="card text-center bg-dark text-white">
        <div class="card-body">
          <h1 class="text-center">LLAMADO DE: <%= @cliente.nombre %></h1>
        </div>
      </div>
   

      
      <table class="table table-dark text-center">
        <thead>
          <tr>
            <th>MOTIVO</th>
            <th>FECHA</th>
            <th>EDITAR</th>
            <th>ELIMINAR</th>
          </tr>
        </thead>
        <tbody>
          <% @llamados.each do |llamado| %>
            <tr>
              <td class="text-center"><%= llamado.motivo %></td>
              <td class="text-center"><%= llamado.fecha %></td>
              <td>
                
                <%= link_to "EDITAR", new_cliente_llamado_path(@cliente, llamado), class: "btn btn-secondary" %>
                
              </td>
               <td>
                
                
                <%= button_to "ELIMINAR", cliente_llamado_path(@cliente, llamado), method: :delete, data: { confirm: "¿Estás seguro de eliminar este llamado?" }, class: "btn btn-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/llamados/new.html.erb
<BR>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-success text-center" role="alert">
      <%= value %>
    </div>
  <% end %>

  <!-- Resto del contenido de la vista -->
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card bg-dark text-white">
        <div class="card-body">
          <h1 class="text-center">AGREGAR LLAMADAS</h1>

          <%= render "form", llamado: @llamado %>

          <br>

          <div class="text-center">
            <%= link_to "REGRESAR", cliente_llamados_path(@cliente), class: "btn btn-secondary" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/llamados/show.html.erb
<div>
  <%= link_to "Edit this llamado",  cliente_llamado_path(@llamado) %> |
  <%= link_to "Back to llamados", cliente_llamados_path(@cliente) %>
  <%= button_to "Destroy this llamado", cliente_llamado_path(@cliente, @llamado), method: :delete %>
</div>