config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios, controllers: {
    sessions: 'usuarios/sessions',
    registrations: 'usuarios/registrations'
  }

  devise_scope :usuario do
    root to: 'usuarios/sessions#new'
    get '/usuarios/sign_out', to: 'usuarios/sessions#destroy', as: :logout_usuario_session
  end

  authenticate :usuario do
    resources :clientes do
      resources :llamados, only: [:index, :show, :new, :create, :edit, :update]
      delete '/llamados/:id', to: 'llamados#destroy', as: 'cliente_llamado'
      

    end
    delete '/clientes/:id', to: 'clientes#destroy', as: 'eliminar_cliente'
    get 'pdf/generate', to: 'pdf#generate', as: 'generate_pdf'
  end
  
  # Resto de las rutas de tu aplicación
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeleventasMarquezcarlos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <%= favicon_link_tag 'favicon.ico' %>
    <%= stylesheet_link_tag "application.css", "data-turbo-track": "reload" %>
   

    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="<%= asset_path('INFORCAP.png') %>" alt="Logo" class="navbar-logo">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <% if usuario_signed_in? %>
              <!-- Menú para usuarios autenticados -->
              <li class="nav-item">
                <%= link_to "Inicio", root_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Cerrar Sesión", destroy_usuario_session_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <!-- Título del menú para usuarios no autenticados -->
              <li class="nav-item">
                <span class="nav-link">Menú</span>
              </li>
            <% end %>
          </ul>
          <% if current_usuario %>
            <div class="navbar-text ml-auto">
              <span id="current-time" class="text-white mr-2"></span>
              <span class="text-white">Bienvenido, <%= current_usuario.email %></span>
            </div>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>

    <script>
      $(document).ready(function() {
        var currentTime = new Date();
        var hours = currentTime.getHours();
        var minutes = currentTime.getMinutes();
        var formattedTime = hours + ":" + (minutes < 10 ? "0" + minutes : minutes);
        $('#current-time').text(formattedTime);
      });
    </script>
  </body>
</html>